---
config:
  layout: elk
  look: neo
  theme: default
---
classDiagram
direction LR
    class Place {
	    - String: id_place
	    +String: title
	    +String: description
	    +float: price
	    +tuple: longitude
	    +list: Amenity
	    create(id_place)
	    update(id_place)
	    delete()
    }
    class Amenity {
	    -String: id_amenity
	    +String: name
	    +String: description
	    list(): Ammenities
	    create(id_amenity)
	    update(id_amenity)
		delete()
    }
    class User {
	    -String: id_user
	    -bool: is_admin
	    +String: first_name
	    -String: last_name
	    -String: email
	    -String: password
	    create(id_user)
	    update(id_user)
	    delete()
    }
    class Review {
	    -String: id_entity
	    +int: rating
	    +String: comment
    }
	class genInfo {
		create()*
		update()*
		delete()*
	}

    Review "1" --> "1" User : author
    Review "1" --> "1" Place : reviews
    Place "1" ..> "*" Amenity : has
    User "1" --> "*" Place : owns
	genInfo "1" <.. "1" User
	genInfo "1" <.. "1" Place
	genInfo "1" <.. "1" Amenity
	genInfo "1" <.. "1" Review
